# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moblie.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pblib.apps_pb2 as apps__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='moblie.proto',
  package='mycell.moblie',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmoblie.proto\x12\rmycell.moblie\x1a\napps.proto\"c\n\x06moblie\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x05model\x18\x02 \x01(\x0e\x32\x14.mycell.moblie.Brand\x12\x12\n\nsystemName\x18\x03 \x01(\t\x12\x12\n\x04\x61pps\x18\x04 \x03(\x0b\x32\x04.App*K\n\x05\x42rand\x12\x0b\n\x07unknown\x10\x00\x12\n\n\x06huawei\x10\x01\x12\n\n\x06xiaomi\x10\x02\x12\x08\n\x04oppo\x10\x03\x12\x08\n\x04vivo\x10\x04\x12\t\n\x05\x61pple\x10\x05\x62\x06proto3'
  ,
  dependencies=[apps__pb2.DESCRIPTOR,])

_BRAND = _descriptor.EnumDescriptor(
  name='Brand',
  full_name='mycell.moblie.Brand',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='huawei', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='xiaomi', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='oppo', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='vivo', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='apple', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=144,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_BRAND)

Brand = enum_type_wrapper.EnumTypeWrapper(_BRAND)
unknown = 0
huawei = 1
xiaomi = 2
oppo = 3
vivo = 4
apple = 5



_MOBLIE = _descriptor.Descriptor(
  name='moblie',
  full_name='mycell.moblie.moblie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mycell.moblie.moblie.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='mycell.moblie.moblie.model', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='systemName', full_name='mycell.moblie.moblie.systemName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apps', full_name='mycell.moblie.moblie.apps', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=142,
)

_MOBLIE.fields_by_name['model'].enum_type = _BRAND
_MOBLIE.fields_by_name['apps'].message_type = apps__pb2._APP
DESCRIPTOR.message_types_by_name['moblie'] = _MOBLIE
DESCRIPTOR.enum_types_by_name['Brand'] = _BRAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

moblie = _reflection.GeneratedProtocolMessageType('moblie', (_message.Message,), {
  'DESCRIPTOR' : _MOBLIE,
  '__module__' : 'moblie_pb2'
  # @@protoc_insertion_point(class_scope:mycell.moblie.moblie)
  })
_sym_db.RegisterMessage(moblie)


# @@protoc_insertion_point(module_scope)
